general.import = [ "~/.config/alacritty/themes/gruvbox.toml" ]

[env]
TERM = "xterm-256color"

[terminal]
shell = "/bin/fish"

[font]
normal = { family = "JetBrainsMono", style = "Regular" }
bold = { family = "JetBrainsMono", style = "Bold" }
italic = { family = "JetBrainsMono", style = "Italic" }
size = 11

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
